### ISSUE TITLE
getBounds returning incorrect values

### ISSUE THREAD

**Issue by alexh00** [DragonBones/DragonBonesAS#11]
I'm testing the Dragon example in Starling. I create my armature and reference the Starling display object it generates through the accessor armature.display. If I call getBounds on that display object, passing through itself as the argument in order to get its own internal co-ordinates and work out what its x and y registration points are, I get a rectangle with incorrect values for the x and y. The values I get seem to be smaller than they should be. I think this is a DragonBones issue, not a Starling issue, although I could be wrong!

**Comment by akdcl** [comment]
You can set slot.transformUpdateEnabled = true to update the slot.display transform in starling :)
