### ISSUE TITLE
Animation.isComplete is true after calling play() on clean armature.animation

### ISSUE THREAD

**Issue by vrobel** [DragonBones/DragonBonesAS#25]
Hi,

I get armature.animation.isComplete value of TRUE when I call play for a newly created Armature instance. I checked the source. Looks like _totalTime is set to 0 play() because it only is calculated from this code:
```actionscript
if(tweenTime >= 0)
{
    _totalTime = tweenTime;
}
else if(tweenEnabled && exMovementID)
{
    _totalTime = _movementData.durationTo;
}
else
{
    _totalTime = 0;
}
```
So it ends up on else because exMovementID is null. But it would also fail when durationTo is 0. Later in code it reads durationTween
`_duration = duration >= 0  duration : _movementData.durationTween;`
Not sure  about it but I think _totalTime should be updated by _duration value i.e.
`_totalTime += _duration`
or isComplete should be updated by _isPlaying value i.e.
```
public function get isComplete():Boolean
{
    return _loop < 0 && _currentTime >= _totalTime && !_isPlaying;
}
```
But I'm not aware of all the logic behind this nor how exactly it works so it's just speculations. Anyway, please fix it :)

The bug relates to the latest 'dev' branch v2.0

**Comment by akdcl** [comment]
Hi, the bug has been fixed
