### ISSUE TITLE
BlendMode not work with DragonBones 2.4.1

### ISSUE THREAD

**Issue by lizistorm** [DragonBones/DragonBonesAS#39]
Set armature.display.blendMode to any mode like BlendMode.SCREEN not work when using 2.4.1

Solution is here:

In DragonBones 2.4.1 XMLDataParser.as(line 178) and ObjectDataParser.as(line 147):

Change
    slotData.blendMode = "normal";
to
    slotData.blendMode = "auto";

Because "auto" mode inherits the blend mode from parent while "normal" mode not.

**Comment by akdcl** [comment]
the bug has been fixed.
