### ISSUE TITLE
Animation control (reset, loop)

### ISSUE THREAD

**Issue by SudoPlz** [DragonBones/DragonBonesAS#48]
Hey guys, 

1) first of all I would like to know how I can reset the animation back to frame 0 after it has successfuly completed?

2) is there a loop property (it would be great if there was an animation.loop property) so that you can set if you want the animation to loop or not on the fly?

Thanks

**Comment by bobrokrol** [comment]
I had same issue year ago and have it right now. Is it possible to reset animation to first frame and stop?

**Comment by akdcl** [comment]
Now, you can use armature.animation.gotoAndStopByTime()
