### ISSUE TITLE
Movieclip within a movieclip problem (cannot reset child).

### ISSUE THREAD

**Issue by SudoPlz** [DragonBones/DragonBonesAS#52]
When having a movieclip animation within a parent movieclip animation, then once the whole things isComplete playing, running `goToAndPlay` will ONLY reset and play again the parent and NOT the child. Is that intended?

**Comment by Tom-Sesselmann** [comment]
We have built a work around for this since it is a common use case for us as well. Would be good if support for this was added to the native code

**Comment by akdcl** [comment]
The bug has been fixed :)
