### ISSUE TITLE
Wrong pivots in StarlingFactory.generateDisplay

### ISSUE THREAD

**Issue by fysx** [DragonBones/DragonBonesAS#56]
If starling TextureAtlas is using and subtextures has frameX and frameY, pivots are growing and animation became bad. if I comment block 				
if(subTextureFrame){
    pivotX += subTextureFrame.x;
    pivotY += subTextureFrame.y;
}
everything works well

**Comment by akdcl** [comment]
Pivots are always center now in db displays.
