### ISSUE TITLE
Pivots are ignored

### ISSUE THREAD

**Issue by alesys** [DragonBones/DragonBonesAS#58]
Panel 3.0.0
DBAS 3.0.1

The animation looks good in the preview panel (it has scale and skew). But when tested in a Starling project, no matter where the register point is placed, the animation will asume the pivot is in the center of the object. 

I'm exporting XML and PNGs, getting everything together in TexturePacker.

**Comment by akdcl** [comment]
the bug has been fixed
https://github.com/DragonBones/DragonBonesAS/commit/c37b512655bc45f4f3a690c88fa751499f8b995e
