### ISSUE TITLE
Event COMPLETE not dispatch when at least one bone Frame Scale is higher than 100%

### ISSUE THREAD

**Issue by tomlefol** [DragonBones/DragonBonesAS#59]
This issue appear with version 3.0. We used 2.4.1 before and with the exact same animation we didn't have the issue.

The event LOOP_COMPLETE works and the animation stop when it should stop but without dispatching the COMPLETE event when a top level bone Frame scale is higher than 100%.

I didn't try with a bone attached to another one yet.

**Comment by akdcl** [comment]
The bug has been fixed :)
