### ISSUE TITLE
New runtime for DragenBones and FastArmature vs Armature Question

### ISSUE THREAD

**Issue by bp74** [DragonBones/DragonBonesAS#64]
Hi,

I've started to work on a port from the AS3 runtime to a Dart/StageXL runtime. Dart is a programming language from Google and compiles to JavaScript. StageXL is a 2D rendering framework for HTML (with support for Canvas and WebGL).

The first results are looking good. The animation is working fine but i'm sure there are still some bugs that need to be fixed.

http://www.stagexl.org/temp/dragon/example.html
https://github.com/bp74/StageXL_DragonBones

I have a question regarding the FastArmature and normal Armature. I thought that i will get some performance benefits from the FastArmature, but it looks as if both implementations perform pretty much the same. So the question is what are the benefits of FastArmature and are they worth it to maintain both code paths?

Another question if you don't mind. Do you have DragonBones animations to test all features of the runtimes? It would be great to have a set of animations for testing. If those animations work correct one could assume that there are not bugs in the runtime.

Thanks a lot and best greetings,
Bernhard

**Comment by bp74** [comment]
Update! I just found the "DragonBones AS Lib V4.1 Release Notes" document and after translating it to engish i now understand that the main benefits for the FastArmature comes from enabling the cache feature. 

After setting up the AnimationCacheManager and enabling the feature the performance is indeed much better, now i understand what is going on :) This is pretty awesome!

**Comment by kevglx** [comment]
oh ok,thanks for the explanation! I didn't understand that I have to initiate the AnimeCacheManager :+1:
