### ISSUE TITLE
Bug in DragonBones example

### ISSUE THREAD

**Issue by neuronix** [DragonBones/DragonBonesAS#68]
Tried the Ubbie example in a simple starling project, you can notice 2 issues:

1. z-order issues on both arms
2. nose position is misplaced when repeating

http://imgur.com/zoPAl65

**Comment by neuronix** [comment]
Update, tried exporting some custom animations, draw order set in the editor seems ignored in the runtime.

**Comment by ze0nni** [comment]
Сonfirm. Wrong z-order is only for Starling. NativeFactory is working good.

**Comment by akdcl** [comment]
The bug has been fixed
