### ISSUE TITLE
Bug with Texture frames and Meshes

### ISSUE THREAD

**Issue by neuronix** [DragonBones/DragonBonesAS#69]
Hi,

If an image is used with a mesh and has a bit of transparency that leads to a texture frame, it will cause an error in starling 1.8 which only allows texture frames on quads.

Current workaround is to remove all excess transparency on images or manually fix the .json texture file but this would need fixing (maybe just not define the frame at all if bone uses a mesh).

**Comment by akdcl** [comment]
The bug has been fixed :)
