### ISSUE TITLE
Mesh animations do not transition to other animations properly

### ISSUE THREAD

**Issue by hedgehog90** [DragonBones/DragonBonesAS#70]
In the newest version of DragonBones, it appears a mesh animation doesn't  transition the vertices of the mesh to the first frame of the new animation. Only if there is a keyframe later on in the animation does it update the vertices correctly.
I'm sure there's a simple fix for this but I haven't found it yet.

![animation](https://cloud.githubusercontent.com/assets/5526342/14797277/e27e4506-0b29-11e6-9e69-f259dbef5c66.gif)

Notice the nose does and face vertices do not move back when I change the animation.

**Comment by superlancelot** [comment]
Have fixed it in the latest version
