### ISSUE TITLE
[Possible BUG] updateFFDTimeline() use FFDTimelineState object before it was inited

### ISSUE THREAD

**Issue by T1mL3arn** [DragonBones/DragonBonesAS#71]
Here [AnimationState.as#L343](https://github.com/DragonBones/DragonBonesAS/blob/master/DragonBones/src/dragonBones/animation/AnimationState.as#L343) is object that is initialized later there [AnimationState.as#L364](https://github.com/DragonBones/DragonBonesAS/blob/master/DragonBones/src/dragonBones/animation/AnimationState.as#L364)

Is may be need to change from this
```as3
var ffdTimelineState:FFDTimelineState;
var i:int = _ffdTimelineStateList.length;
var slot:Slot;
while (i --)
{
	ffdTimelineState = _ffdTimelineStateList[i];
	slot = _armature.getSlot(ffdTimelineState.name);
	if (!slot || slot.displayIndex != ffdTimelineState.displayIndex)
	{
		_ffdTimelineStateList.splice(i, 1);
		FFDTimelineState.returnObject(timelineState);
```
to that ?
```as3
var ffdTimelineState:FFDTimelineState;
var i:int = _ffdTimelineStateList.length;
var slot:Slot;
while (i --)
{
	ffdTimelineState = _ffdTimelineStateList[i];
	slot = _armature.getSlot(ffdTimelineState.name);
	if (!slot || slot.displayIndex != ffdTimelineState.displayIndex)
	{
		_ffdTimelineStateList.splice(i, 1);
		FFDTimelineState.returnObject(ffdTimelineState);
```

**Comment by Fisa212** [comment]
i previously never get problem regarding that issue. can u explain what's the problem and when does it  happen?

**Comment by T1mL3arn** [comment]
```timelineState``` is used in ```FFDTimelineState.returnObject(timelineState);``` BEFORE its initalization. Here is using [AnimationState.as#L343](https://github.com/DragonBones/DragonBonesAS/blob/master/DragonBones/src/dragonBones/animation/AnimationState.as#L343) but initialization is later here [AnimationState.as#L364](https://github.com/DragonBones/DragonBonesAS/blob/master/DragonBones/src/dragonBones/animation/AnimationState.as#L364). Seems a null-object is passed back to the pool.

I can't point a real problem when using DB in as3 projects. I am porting DB to Haxe and Haxe does not allow to use variable before its initializing.

**Comment by akdcl** [comment]
The bug has been fixed :)
