### ISSUE TITLE
What kind of method instead addTextureAtlas in 4.7?

### ISSUE THREAD

**Issue by Dragosha** [DragonBones/DragonBonesAS#78]
In 4.6 we can add a ready to use TextureAtlas from Starling to factory, pre-created in AssetManager, for example:
factory.addTextureAtlas(assets.getTextureAtlas("MyAtlas"));
in 4.7 this method was removed and added parseTextureAtlasData. But it not accept TextureAtlas.

How I can add TextureAtlas to factory?

**Comment by akdcl** [comment]
Hi,
You can addTextureAtlas like this:
factory.addTextureAtlas(StarlingTextureAtlasData.fromTextureAtlas(assets.getTextureAtlas("MyAtlas")));

**Comment by Dragosha** [comment]
Did you mean factory.**addTextureAtlasData**(StarlingTextureAtlasData.fromTextureAtlas(assets.getTextureAtlas("MyAtlas"))); ?
Thanks, it works!
