### ISSUE TITLE
Lost context for Starling 1.x

### ISSUE THREAD

**Issue by mistergreen** [DragonBones/DragonBonesAS#81]
Starling 1.8

DB 4.7

private var factory:StarlingFactory 

define StarlingFactory causes starling context missing,            

> Error: Starling context is missing
> 	at starling.textures::Texture$/empty()[/Users/redge/Dropbox/Development/starling/starling/src/starling/textures/Texture.as:449]
> 	at dragonBones.starling::StarlingSlot$cinit()[/Users/minh/Documents/peewee/Source Library/DragonBonesAS-master/Starling/Starling_1.x/src/dragonBones/starling/StarlingSlot.as:29]
> 	at global$init()

**Comment by akdcl** [comment]
Hi,
I can't reproduce this bug, could you provid a demo?

**Comment by mistergreen** [comment]
hmm,
Here are my simple source files.
I'm using AIR 21, Starling 1.8, latest DragonBones master (4.7).
It works fine with Starling 2.x

[src.zip](https://github.com/DragonBones/DragonBonesAS/files/413332/src.zip)

**Comment by freem-trg** [comment]
Such kind of bugs usually easy to reproduce with manual call of Starling.context.dispose();

**Comment by akdcl** [comment]
Hi,
I still can not reproduce this bug, the demo works fine in flash build and flash pro.
Test in AIR 21, Starling 1.8, latest DragonBonesAS master.

**Comment by mistergreen** [comment]
hmm, I'm not sure what I'm doing wrong. I include the DragonBones/src AND Starling/Straling_1.x/src to my Library path.

**Comment by mistergreen** [comment]
Here's a video explaining the problem

https://youtu.be/I-jW6f5Z8w4

**Comment by akdcl** [comment]
Hi,
Thank you for the video,  I'm not sure if the bug was been fixed. The starling empty texture initialization change to laze manner.

**Comment by mistergreen** [comment]
I tested dragon bones 4.5 with starling 1.8 and it works. So there is a bug in the update to 4.7.

**Comment by mistergreen** [comment]
Awesome, I saw the new commit. The bug is fixed.
