### ISSUE TITLE
DragonBones 4.7 mesh issue with Starling 1.8

### ISSUE THREAD

**Issue by mistergreen** [DragonBones/DragonBonesAS#82]
Hey,
The mesh works with Starling 2.0 but doesn't work in Starling 1.8
There are no errors. It just doesn't function. Here's a video showing the issue.

https://youtu.be/kTtOExq04EE

**Comment by akdcl** [comment]
Hi,
Starling 1.x can not support mesh, if want to support it, we had to discard other features, like set slot.display, childArmature and so on.

**Comment by mistergreen** [comment]
Ok. It would have been nice to have mesh support.
