### ISSUE TITLE
Is there a way to Scale armature.display with smooth texture?

### ISSUE THREAD

**Issue by mistergreen** [DragonBones/DragonBonesAS#83]
I'm using Starling 1.8
DragonBones 4.7

When I scale the the armature display to something like

> 			armature = factory.buildArmature("hero");
			armatureDisplay = armature.display as StarlingArmatureDisplay;
			armatureDisplay.scaleX = 0.2;
			armatureDisplay.scaleY = 0.2;

The texture is very blocky where there is no smoothing. Is there a way to set a smoothing to the textures?

I know starling has starling.textures.TextureSmoothing

**Comment by akdcl** [comment]
Hi, 
You can get starling texture like this:
starlingTexture = (factory.getTextureAtlasData("dbDataName")[0] as StarlingTextureAtlasData).texture;

**Comment by mistergreen** [comment]
Actually the smoothing is with the Image class. I've tried

```
			var head:Image = factory.getTextureDisplay("textureName","dragonBonesName");
			head.smoothing = starling.textures.TextureSmoothing.BILINEAR;
```

But I keep getting null. I can't find the correct "textureName","dragonBonesName". What do they refer too?

**Comment by akdcl** [comment]
Hi,
You can expends StarlingFactory to modify slot and image.
`MyFactory extends StarlingFactory
{
    override _generateSlot():Slot
    {
        const slot = super._generateSlot();
        const image = (slot.rawDisplay as Image);
    }
}`

**Comment by mistergreen** [comment]
Sorry, the antialias smoothing is a problem with the game engine I'm using, not dragonbones.
