### ISSUE TITLE
slot getBounds() for collision detection

### ISSUE THREAD

**Issue by mistergreen** [DragonBones/DragonBonesAS#84]
I'm trying to get the bounds of a slot.display but all I'm getting is a static rectangle. 
I'm using starling 1.8, DB 4.7

```
_armatureDisplay = _dog.display as StarlingArmatureDisplay;
_arm_right_slot = _dog.getSlot("dog_arm2").display.getBounds(_armatureDisplay);
```

I can't find a transformUpdateEnabled = true for Slot.

**Comment by akdcl** [comment]
Set transformUpdateEnabled to true, before armature advanceTime.
```
armature = buildArmature();
armature.getSlot(xxx).transformUpdateEnabled = true;

...

armature.getSlot(xxx).display.getBounds(armature.display);
```

**Comment by mistergreen** [comment]
Thanks, it works sort of.
`(armature.getSlot(xxx) as StarlingSlot).transformUpdateEnabled = true;`

This helps to get the changes in the bones transformation but getBounds() still returns a static rectangle.

This works when I get the x,y,width, height of the display.
```
(_dog.getSlot("dog_arm2") as StarlingSlot).transformUpdateEnabled = true;
_arm_right_slot = _dog.getSlot("dog_arm2").display;
trace(_arm_right_slot.x+":"+_arm_right_slot.y+":"+_arm_right_slot.width);
```

I guess this will do.

**Comment by mistergreen** [comment]
My mistake, I needed to put 
armature.getSlot(xxx).display.getBounds(armature.display);
in a display loop to get the change.
