### ISSUE TITLE
Assetmanager & multi-resolution problem

### ISSUE THREAD

**Issue by mistergreen** [DragonBones/DragonBonesAS#86]
I export my DB 4.7 animation out at the scale of 1 and .5.
The scale 1 is for bigger resolution and .5 for smaller resolution.

In Starling, I use the Assetmanager to load the texture and atlas.
It works fine for lower resolution, contentScale = 1. But the texture atlas is all wrong with higher resolution, contentScale = 2

`Constants.assets = new AssetManager(contentScale, true); `

If I manually set contentScale to 1 with the higher resolution, the DB renders the atlasTexture correctly but of course this messes with other graphics in starling.

**Comment by mistergreen** [comment]
The closest solution I found is to pass in the scale Factor into parseTextureAtlasData

`Constants.factory.parseTextureAtlasData( Constants.assets.getObject("texture"), Constants.assets.getTexture("texture"),"peewee", Constants.scaleFactor);`

But it looks like the armature data is off. They don't connect.
[https://www.flickr.com/gp/professorminh/cvz105](url)

**Comment by akdcl** [comment]
Hi,
This bug has been fixed in the dev branch and added an example about how to use multi resolution textureAtlas.

**Comment by mistergreen** [comment]
Great, looks like it work. Make sure to use only the original normal resolution DBData json file.
